# Generated by Django 4.0.5 on 2022-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verify_number',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
