# Generated by Django 4.0.5 on 2022-07-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_verify_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verify_number',
        ),
    ]
