# Generated by Django 4.0.4 on 2022-07-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_users_verify_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='description',
            new_name='subcategory',
        ),
    ]
