# Generated by Django 4.0.4 on 2022-07-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_sector_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
