# Generated by Django 4.0.5 on 2022-09-15 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
