# Generated by Django 4.0.5 on 2022-09-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_joined',
            new_name='created_date',
        ),
    ]
