# Generated by Django 4.0.5 on 2022-09-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_date_joined_project_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='competitor_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='competitor_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='competitor_5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
