# Generated by Django 4.0.5 on 2022-09-21 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_project_competitor_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
