# Generated by Django 4.0.8 on 2022-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_company_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook',
            name='fb_engagement_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='instagram',
            name='insta_engagement_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='twitter',
            name='twitter_engagement_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='youtube',
            name='youtube_engagement_rate',
            field=models.BigIntegerField(null=True),
        ),
    ]
