# Generated by Django 4.0.8 on 2022-11-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_facebook_fb_engagement_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='fb_engagement_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='insta_engagement_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='twitter_engagement_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='youtube_engagement_rate',
            field=models.FloatField(null=True),
        ),
    ]
