# Generated by Django 4.0.8 on 2022-12-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_facebook_fb_engagement_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeenCircle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuponCode', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
