# Generated by Django 4.0.8 on 2022-12-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_company_facebook_url_company_instagram_url_and_more')    
    ]

    operations = [
    ]
