# Generated by Django 4.0.8 on 2023-01-16 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20221214_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('facebook_url', models.CharField(max_length=255, null=True)),
                ('instagram_url', models.CharField(max_length=255, null=True)),
                ('twitter_url', models.CharField(max_length=255, null=True)),
                ('youtube_url', models.CharField(max_length=255, null=True)),
                ('company_id', models.BigIntegerField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project')),
            ],
        ),
    ]
