# Generated by Django 4.0.8 on 2023-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_links',
            name='company_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
