# Generated by Django 4.0.8 on 2023-01-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_social_links_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_links',
            name='id',
        ),
        migrations.AlterField(
            model_name='social_links',
            name='company_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.project'),
            preserve_default=False,
        ),
    ]
