# Generated by Django 4.0.8 on 2023-02-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_paid_est_cpc_budget_performance_paid_est_ppc_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='web_avg_time',
        ),
        migrations.AlterField(
            model_name='performance',
            name='instagram_avg_comments',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='instagram_avg_likes',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='instagram_total_followers',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='instagram_total_posts',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='twitter_avg_likes',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='twitter_avg_replies',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='twitter_avg_retweets',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='twitter_total_followers',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='twitter_total_following',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='youtube_total_comments',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='youtube_total_likes',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='youtube_total_videos',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='youtube_total_views',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
