# Generated by Django 4.0.8 on 2023-02-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_performance_web_avg_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='youtube_total_comments',
            new_name='twitter_tweet_count',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='seo_avg_keywords',
            new_name='web_avg_time',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='seo_traffic_value',
        ),
        migrations.AddField(
            model_name='performance',
            name='youtube_subscriber_count',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
