# Generated by Django 4.0.8 on 2023-03-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_youtube_total_comments_performance_twitter_tweet_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='project_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
