# Generated by Django 4.0.8 on 2023-03-27 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_social_media_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitchInputs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_domain', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('value_proposition', models.CharField(max_length=255, null=True)),
                ('key_differentiator_1', models.CharField(max_length=255, null=True)),
                ('key_differentiator_description_1', models.CharField(max_length=255, null=True)),
                ('key_differentiator_2', models.CharField(max_length=255, null=True)),
                ('key_differentiator_description_2', models.CharField(max_length=255, null=True)),
                ('key_differentiator_3', models.CharField(max_length=255, null=True)),
                ('key_differentiator_description_3', models.CharField(max_length=255, null=True)),
                ('client_1', models.CharField(max_length=255, null=True)),
                ('client_description_1', models.CharField(max_length=255, null=True)),
                ('client_2', models.CharField(max_length=255, null=True)),
                ('client_description_2', models.CharField(max_length=255, null=True)),
                ('client_3', models.CharField(max_length=255, null=True)),
                ('client_description_3', models.CharField(max_length=255, null=True)),
                ('opportunity_1', models.CharField(max_length=255, null=True)),
                ('opportunity_description_1', models.CharField(max_length=255, null=True)),
                ('opportunity_2', models.CharField(max_length=255, null=True)),
                ('opportunity_description_2', models.CharField(max_length=255, null=True)),
                ('opportunity_3', models.CharField(max_length=255, null=True)),
                ('opportunity_description_3', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
