# Generated by Django 4.0.8 on 2023-03-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_pitchinputs_client_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
