# Generated by Django 4.0.8 on 2023-03-27 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_pitchinputs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
