# Generated by Django 4.0.8 on 2023-05-15 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pitchinputs_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_model',
            fields=[
                ('website_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_date', models.DateTimeField(auto_now=True)),
                ('mobile_page_speed', models.FloatField(max_length=255, null=True)),
                ('desktop_page_speed', models.FloatField(max_length=255, null=True)),
                ('bounce_rate', models.FloatField(max_length=255, null=True)),
                ('monthly_traffic', models.FloatField(max_length=255, null=True)),
                ('pages_visit', models.FloatField(max_length=255, null=True)),
                ('avg_TimeOnSite', models.CharField(max_length=255, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
        ),
    ]
