# Generated by Django 4.0.8 on 2023-05-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_copy_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_model',
            name='data_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='website_traffic',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.website_model'),
        ),
    ]
