# Generated by Django 4.0.8 on 2023-05-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_website_model_data_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_model',
            new_name='Website_data',
        ),
    ]
