# Generated by Django 4.0.8 on 2023-05-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_website_model_website_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media_data',
            fields=[
                ('social_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_date', models.DateTimeField(auto_now=True)),
                ('global_engagement_rate', models.FloatField(max_length=255, null=True)),
                ('total_followers', models.BigIntegerField(null=True)),
                ('total_average_interactions', models.FloatField(max_length=255, null=True)),
                ('total_clicks', models.BigIntegerField(null=True)),
                ('project_id', models.BigIntegerField(default=0)),
                ('data_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Seo_data',
            fields=[
                ('seo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_date', models.DateTimeField(auto_now=True)),
                ('organic_traffic', models.FloatField(max_length=255, null=True)),
                ('web_authority', models.FloatField(max_length=255, null=True)),
                ('total_keywords', models.FloatField(max_length=255, null=True)),
                ('avg_keywords_search', models.FloatField(max_length=255, null=True)),
                ('traffic_value', models.FloatField(max_length=255, null=True)),
                ('paid_traffic', models.FloatField(max_length=255, null=True)),
                ('estimatedCPC', models.FloatField(max_length=255, null=True)),
                ('paid_keywords', models.FloatField(max_length=255, null=True)),
                ('estm_ppc_budget', models.FloatField(max_length=255, null=True)),
                ('backlinks', models.FloatField(max_length=255, null=True)),
                ('referring_domains', models.FloatField(max_length=255, null=True)),
                ('avg_organic_rank', models.FloatField(max_length=255, null=True)),
                ('data_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
            ],
        ),
    ]
