# Generated by Django 4.0.8 on 2023-05-15 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_copy_data copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.social_media_data'),
        ),
        migrations.AlterField(
            model_name='instagram',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.social_media_data'),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.social_media_data'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='social_media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.social_media_data'),
        ),
    ]
