# Generated by Django 4.0.8 on 2023-05-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_facebook_social_media_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seo',
            new_name='Seo_s',
        ),
        migrations.RenameModel(
            old_name='Social_media',
            new_name='Social_media_s',
        ),
        migrations.RenameModel(
            old_name='Website',
            new_name='Website_s',
        ),
    ]
