# Generated by Django 4.0.8 on 2023-05-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_rename_seo_seo_s_rename_social_media_social_media_s_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seo_data',
            new_name='Seo',
        ),
        migrations.RenameModel(
            old_name='Social_media_data',
            new_name='Social_media',
        ),
        migrations.RenameModel(
            old_name='Website_data',
            new_name='Website',
        ),
    ]
