# Generated by Django 4.0.8 on 2023-06-15 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_social_media_s_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchinputs',
            old_name='user',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_description_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_description_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='client_description_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_description_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_description_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='key_differentiator_description_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_description_1',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_description_2',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='opportunity_description_3',
        ),
        migrations.RemoveField(
            model_name='pitchinputs',
            name='value_proposition',
        ),
        migrations.AddField(
            model_name='pitchinputs',
            name='status',
            field=models.BigIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='pitchinputs',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
