# Generated by Django 4.0.8 on 2023-06-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_user_pitchinputs_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
