# Generated by Django 4.0.8 on 2023-06-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_pitchinputs_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchinputs',
            name='template',
            field=models.BigIntegerField(default=True),
        ),
    ]
