# Generated by Django 4.0.8 on 2023-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_pitchinputs_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='brief',
            field=models.CharField(max_length=4000),
        ),
    ]
