# Generated by Django 4.0.8 on 2023-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_pitchinputs_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='status',
            field=models.BigIntegerField(default=False),
        ),
    ]
