# Generated by Django 4.0.8 on 2023-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_pitchinputs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchinputs',
            name='brief',
            field=models.TextField(),
        ),
    ]
