# Generated by Django 4.0.8 on 2023-09-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_keencircle'),
        ('api', '0045_alter_pitchinputs_brief'),
    ]

    operations = [
    ]
